# config/config.yaml
model:
  input_dim: 10
  hidden_dim: 50
  output_dim: 1
  lr: 0.001

trainer:
  max_epochs: 200
  accelerator: 'gpu'
  # strategy: 'ddp'
  # devices: 1
  # num_nodes: 1
  enable_progress_bar: true

hydra:
  run:
    dir: outputs/requeue_exp
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}