# config/config.yaml
model:
  input_dim: 10
  hidden_dim: 50
  output_dim: 1
  lr: 0.001

trainer:
  max_epochs: 200
  resume_from_checkpoint: null
  strategy: null
  accelerator: 'gpu'
  devices: 1

hydra:
  run:
    dir: outputs/exp
  sweep:
    dir: multirun/exp
    subdir: ${hydra.job.num}